language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database diary;' -U postgres
script:
  - npm run test 
after_script:
  - npm run coverage